export const tabledata = [
  {
    name: "Sunil Joshi",
    post: "Web Designer",
    need:"Facebook ADS",
    email: "suniljoshi@gmail.com",
    createdOn: "12 Oct 2023",
    modifiedOn: "15 Oct 2023",
    status: "Active",
  },
  {
    name: "Andrew McDownland",
    post: "Project Manager",
    need:"Facebook ADS",
    email: "andrew@example.com",
    createdOn: "18 Sep 2023",
    modifiedOn: "20 Sep 2023",
    status: "Inactive",
  },
  {
    name: "Christopher Jamil",
    post: "UI/UX Designer",
    need:"Facebook ADS",
    email: "chris@example.com",
    createdOn: "5 Nov 2023",
    modifiedOn: "8 Nov 2023",
    status: "Active",
  },
  {
    name: "Nirav Joshi",
    post: "Frontend Engineer",
    need:"Facebook ADS",
    email: "nirav@example.com",
    createdOn: "7 Oct 2023",
    modifiedOn: "10 Oct 2023",
    status: "Active",
  },
  {
    name: "Sara Thompson",
    post: "Software Developer",
    need:"Facebook ADS",
    email: "sara@example.com",
    createdOn: "15 Dec 2023",
    modifiedOn: "18 Dec 2023",
    status: "Inactive",
  },
  {
    name: "Alex Smith",
    post: "Backend Developer",
    need:"Facebook ADS",
    email: "alex@example.com",
    createdOn: "3 Jan 2023",
    modifiedOn: "6 Jan 2023",
    status: "Active",
  },
  {
    name: "Emily Davis",
    post: "Content Writer",
    need:"Facebook ADS",
    email: "emily@example.com",
    createdOn: "21 Feb 2023",
    modifiedOn: "25 Feb 2023",
    status: "Inactive",
  },
  {
    name: "John Doe",
    post: "Marketing Specialist",
    need:"Facebook ADS",
    email: "john@example.com",
    createdOn: "9 Mar 2023",
    modifiedOn: "12 Mar 2023",
    status: "Active",
  },
  {
    name: "Ella Brown",
    post: "Sales Executive",
    need:"Facebook ADS",
    email: "ella@example.com",
    createdOn: "14 Apr 2023",
    modifiedOn: "17 Apr 2023",
    status: "Active",
  },
  {
    name: "Michael Wilson",
    post: "Customer Support",
    need:"Facebook ADS",
    email: "michael@example.com",
    createdOn: "2 May 2023",
    modifiedOn: "5 May 2023",
    status: "Inactive",
  },
  {
    name: "Sunil Joshi",
    post: "Web Designer",
    need:"Facebook ADS",
    email: "suniljoshi@gmail.com",
    createdOn: "12 Oct 2023",
    modifiedOn: "15 Oct 2023",
    status: "Active",
  },
  {
    name: "Andrew McDownland",
    post: "Project Manager",
    need:"Facebook ADS",
    email: "andrew@example.com",
    createdOn: "18 Sep 2023",
    modifiedOn: "20 Sep 2023",
    status: "Inactive",
  },
  {
    name: "Christopher Jamil",
    post: "UI/UX Designer",
    need:"Facebook ADS",
    email: "chris@example.com",
    createdOn: "5 Nov 2023",
    modifiedOn: "8 Nov 2023",
    status: "Active",
  },
  {
    name: "Nirav Joshi",
    post: "Frontend Engineer",
    need:"Facebook ADS",
    email: "nirav@example.com",
    createdOn: "7 Oct 2023",
    modifiedOn: "10 Oct 2023",
    status: "Active",
  },
  {
    name: "Sara Thompson",
    post: "Software Developer",
    need:"Facebook ADS",
    email: "sara@example.com",
    createdOn: "15 Dec 2023",
    modifiedOn: "18 Dec 2023",
    status: "Inactive",
  },
  {
    name: "Alex Smith",
    post: "Backend Developer",
    need:"Facebook ADS",
    email: "alex@example.com",
    createdOn: "3 Jan 2023",
    modifiedOn: "6 Jan 2023",
    status: "Active",
  },
  {
    name: "Emily Davis",
    post: "Content Writer",
    need:"Facebook ADS",
    email: "emily@example.com",
    createdOn: "21 Feb 2023",
    modifiedOn: "25 Feb 2023",
    status: "Inactive",
  },
  {
    name: "John Doe",
    post: "Marketing Specialist",
    need:"Facebook ADS",
    email: "john@example.com",
    createdOn: "9 Mar 2023",
    modifiedOn: "12 Mar 2023",
    status: "Active",
  },
  {
    name: "Ella Brown",
    post: "Sales Executive",
    need:"Facebook ADS",
    email: "ella@example.com",
    createdOn: "14 Apr 2023",
    modifiedOn: "17 Apr 2023",
    status: "Active",
  },
  {
    name: "Michael Wilson",
    post: "Customer Support",
    need:"Facebook ADS",
    email: "michael@example.com",
    createdOn: "2 May 2023",
    modifiedOn: "5 May 2023",
    status: "Inactive",
  },
];
