export const tabledata = [
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Failed",
  },
  {
    fileName: "zoom_info_data.xlsx",
    folderName: "Zoominfo",
    uploadDate: "12 Oct 2023",
    uploadTime: "1:30 PM",
    status: "Success",
  },
];
